wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696190345.480155
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 85
      - 98
      - 105
      3:
      - 4
      - 13
      - 15
      - 23
      - 42
      4: 3.8.10
      5: 0.15.8
      6: 4.32.0
      8:
      - 5
